name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  npm-package:
    name: NPM package (build + test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci

      - run: npm run build

      - run: npm test

  plugin-assets:
    name: Plugin assets (build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci
        working-directory: plugin-assets

      - run: npm run build
        working-directory: plugin-assets
